### ISSUE TITLE
Juke box

### ISSUE THREAD

**Issue by simplebunsen** [djpadbit/Sound-Physics#13] opened 2019-08-04 16:46 UTC
Using the latest version, and the jukebox doesn't seem to be affected by mod sound mechanics at all, except for randomly muting/sounding muffled when pressing escape to pause in singleplayer. Another pause unpause cycle fixes it.

I'm unsure what info I can provide to help you fix it...

**Comment by djpadbit** [comment] 2019-08-04 17:38
The jukebox isn't supposed to be affected by sound physics, because of how it is implemented, the environment would only be calculated once when the jukebox starts playing and would not get muffled when going behind walls or the reverb wouldn't change when remove and adding blocks. (Although it update the environment with the dynamic environment evaluation, i still don't recommend using it)

**Comment by simplebunsen** [comment] 2019-08-04 19:21
ok that's understandable. Still the pause bug exists.

**Comment by djpadbit** [comment] 2019-08-04 22:17
I can't seem to be able to reproduce it. What happens specifically ?

**Comment by djpadbit** [comment] 2020-02-21 13:27
I'll close this issue. If needed I'll reopen it.

**Closed by djpadbit** 2020-02-21 13:27 UTC

**Comment by Lgmrszd** [comment] 2020-05-29 20:39
Pause bug @simplebunsen was talking about is the effect of environment being recalculated after pausing the game.
Steps to reproduce:

1. Place Jukebox inside closed area and put music disc in it.
2. Leave that area or just do anything to change sound effect conditions — played music is not affected.
3. Pause game and then un-pause it — now playing music is affected by new conditions.

It seems that it can be possible to make jukebox be affected by sounds physics (do refresh several times per second, not sure how that would affect game performance though), or just fix refreshing after pause (although this way it won't bee that cool)

**Comment by Lgmrszd** [comment] 2020-05-29 22:20
Testing in separate instance, looks like some mod makes jukebox pause the music while game is paused, I'll investigate later which mod does this.
