### ISSUE TITLE
Makes 1.12.2 dynamic surrounding sound sound really quiet

### ISSUE THREAD

**Issue by CorneliusCornbread** [djpadbit/Sound-Physics#18] opened 2019-09-01 03:03 UTC
I'm not sure what it is, but after installing this mod, dynamic surroundings sounds (eg. crafting, sword equip and swing) sound REALLY quiet. No slider in-game or config file in dynamic surroundings changed anything.

Hoping this gets patched, as it's the only thing that's currently making me use sound filters over this. (Other than sound filters being on curse)

**Comment by djpadbit** [comment] 2019-09-01 12:36
Ah yes, i noticed this bug quite a while back, the problem is that dynamic surroundings tracking sounds (so the equip, crafting, swing and stuff) use position for attenuation. So to Sound Physics the sounds are 32 block over you so it makes sense that you can't really hear them. I was hoping it could get fixed in dynamic surroundings but the development seems stopped so i'll try and make a patch within Sound Physics. For now you can use the dynamic surroundings version that i modified to remove the attenuation [DynamicSurroundings-1.12.2-3.5.4.3.zip](https://github.com/djpadbit/Sound-Physics/files/3563465/DynamicSurroundings-1.12.2-3.5.4.3.zip) witch shouldn't have the problem but when you go too fast the tracking sounds will kind of fade in and out faintly and also there isn't any attenuation to replace the one that was in place (kind of a hack).

Also i'll try and look into putting Sound Physics on curse but i'd have to get the permission from Sonic Ether and Daipenger.

**Comment by djpadbit** [comment] 2019-09-01 16:09
Alright, it should be fixed in https://github.com/djpadbit/Sound-Physics/commit/fca2c27c96098543c763391d9f746efcd5809196, Here's a build with the fixes [Sound-Physics-1.12.2.zip](https://github.com/djpadbit/Sound-Physics/files/3563676/Sound-Physics-1.12.2.zip). I'm closing the issue.

**Closed by djpadbit** 2019-09-01 16:09 UTC

**Comment by CorneliusCornbread** [comment] 2019-09-01 18:51
Awesome, thanks
